name: 1.0.0$(Rev:.r)
resources:
- repo: self
  clean: true

jobs:

# ------- Windows -------------------------------------------------------------
- job: BuildWindows
  displayName: win-x64
  condition: succeeded()
  pool:
    name: Hosted VS2017
    demands:
    - msbuild
    - visualstudio

  steps:
  - checkout: self
    clean: true
    submodules: true
    
  - task: UsePythonVersion@0
    displayName: 'Use Python 2.x'
    inputs:
      versionSpec: 2.x
  
  #--------- arm ---------
  - task: CMake@1
    displayName: 'Cmake arm'
    inputs:
      cmakeArgs: '-G "Visual Studio 15 2017" -A ARM'
      workingDirectory: libuv

  - task: VSBuild@1
    displayName: 'Build solution libuv.sln arm'
    inputs:
      solution: libuv\libuv.sln
      vsVersion: 15.0
      platform: arm
      configuration: release
      clean: true
      
  - task: CmdLine@2
    displayName: 'Create contents directory arm'
    inputs:
      script: 'mkdir contents\runtimes\win-arm\native'

  - task: CmdLine@2
    displayName: 'Copy libuv.dll to content directory arm'
    inputs:
      script: 'copy libuv\release\uv.dll contents\runtimes\win-arm\native\libuv.dll'

  #--------- x64 ---------
  - task: CmdLine@2
    displayName: 'Clean libuv'
    inputs:
      script: 'git clean -xfd'
      workingDirectory: libuv

  - task: CMake@1
    displayName: 'Cmake x64'
    inputs:
      cmakeArgs: '-DBUILD_TESTING=ON -G "Visual Studio 15 2017" -A x64'
      workingDirectory: libuv
      
  - task: VSBuild@1
    displayName: 'Build solution libuv.sln x64'
    inputs:
      solution: libuv\libuv.sln
      vsVersion: 15.0
      platform: x64
      configuration: release
      clean: true

  - task: CmdLine@2
    displayName: 'Run tests x64'
    inputs:
      script: 'release\uv_run_tests.exe'
      workingDirectory: libuv

  - task: CmdLine@2
    displayName: 'Create contents directory x64'
    inputs:
      script: 'mkdir contents\runtimes\win-x64\native'

  - task: CmdLine@2
    displayName: 'Copy libuv.dll to content directory x64'
    inputs:
      script: 'copy libuv\release\uv.dll contents\runtimes\win-x64\native\libuv.dll'
  #--------- /x64 ---------

  #--------- x86 ---------
  - task: CmdLine@2
    displayName: 'Clean libuv'
    inputs:
      script: 'git clean -xfd'
      workingDirectory: libuv

  - task: CMake@1
    displayName: 'Cmake x64'
    inputs:
      cmakeArgs: '-DBUILD_TESTING=ON -G "Visual Studio 15 2017" -A Win32'
      workingDirectory: libuv
      
  - task: VSBuild@1
    displayName: 'Build solution libuv.sln x86'
    inputs:
      solution: libuv\libuv.sln
      vsVersion: 15.0
      platform: WIN32
      configuration: release
      clean: true

  - task: CmdLine@2
    displayName: 'Run tests x86'
    inputs:
      script: 'release\uv_run_tests.exe'
      workingDirectory: libuv

  - task: CmdLine@2
    displayName: 'Create contents directory x86'
    inputs:
      script: 'mkdir contents\runtimes\win-x86\native'

  - task: CmdLine@2
    displayName: 'Copy libuv.dll to content directory x86'
    inputs:
      script: 'copy libuv\release\uv.dll contents\runtimes\win-x86\native\libuv.dll'
  #--------- /x86 ---------

  - task: NuGetCommand@2
    displayName: 'Create nuget package'
    inputs:
      command: pack
      packagesToPack: Internal.libuv-Windows.nuspec
      versioningScheme: byBuildNumber
      
  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: push
      publishVstsFeed: '/be2f0cee-544d-407b-b4bf-6dcb58c6e898'
      versioningScheme: byBuildNumber

# ------- Linux -------------------------------------------------------------
- job: BuildLinux
  displayName: linux-x64
  condition: succeeded()
  pool:
    name: Hosted Ubuntu 1604
  steps:
  - checkout: self
    clean: true
    submodules: true
    
  - task: UsePythonVersion@0
    displayName: 'Use Python 2.x'
    inputs:
      versionSpec: 2.x

  - task: PythonScript@0
    displayName: 'Generate make file'
    inputs:
      scriptPath: 'gyp/gyp_main.py'
      arguments: '-I common.gypi test/test.gyp -f make --depth=. -Duv_library=shared_library -Dtarget_arch=x64'
      workingDirectory: libuv

  - task: Bash@3
    displayName: 'Build'
    inputs:
      targetType: inline
      script: 'BUILDTYPE=Release make'
      workingDirectory: libuv

  - task: Bash@3
    displayName: 'Run tests'
    inputs:
      targetType: inline
      script: 'out/Release/run-tests'
      workingDirectory: libuv
      
  - task: Bash@3
    displayName: 'Create contents directory'
    inputs:
      targetType: inline
      script: 'mkdir -p contents/runtimes/linux-x64/native'

  - task: Bash@3
    displayName: 'Copy libuv.so to content directory'
    inputs:
      targetType: inline
      script: 'cp libuv/out/Release/lib.target/libuv.so.1 contents/runtimes/linux-x64/native/libuv.so'
      
  - task: NuGetCommand@2
    displayName: 'Create nuget package'
    inputs:
      command: pack
      packagesToPack: Internal.libuv-Linux.nuspec
      versioningScheme: byBuildNumber
      
  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: push
      publishVstsFeed: '/be2f0cee-544d-407b-b4bf-6dcb58c6e898'
      versioningScheme: byBuildNumber

# ------- Darwin -------------------------------------------------------------
- job: BuildDarwin
  displayName: osx-x64
  condition: succeeded()
  pool:
    name: Hosted macOS High Sierra
  steps:
  - checkout: self
    clean: true
    submodules: true

  - task: UsePythonVersion@0
    displayName: 'Use Python 2.x'
    inputs:
      versionSpec: 2.x

  - task: Bash@3
    displayName: 'Bash Script'
    inputs:
      targetType: filePath
      filePath: './build-osx-x64.sh'

  - task: Bash@3
    displayName: 'Create contents directory'
    inputs:
      targetType: inline
      script: 'mkdir -p contents/runtimes/osx/native'

  - task: Bash@3
    displayName: 'Copy libuv.dylib to content directory'
    inputs:
      targetType: inline
      script: 'cp libuv/build/Release/libuv.dylib contents/runtimes/osx/native'

  - task: NuGetCommand@2
    displayName: 'Create nuget package'
    inputs:
      command: pack
      packagesToPack: Internal.libuv-Darwin.nuspec
      versioningScheme: byBuildNumber

  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: push
      publishVstsFeed: '/be2f0cee-544d-407b-b4bf-6dcb58c6e898'
      versioningScheme: byBuildNumber
